services:
    app.mongo_client:
        class: MongoClient
        arguments:
            - 'mongodb://localhost:27017'

    app.mongo_db:
        class: MongoDB
        factory_service: mongo_client
        factory_method:  selectDB
        arguments: ['%app.mongodb.dbname%']

    app.controller.dashboard:
        class: App\Controller\DashboardController
        arguments:
            - '@app.dashboard.decider'
            - '@jms_serializer'

    app.dashboard.decider:
        class: App\Dashboard\Decider
        arguments:
            - '@app.dashboard'
            - '@github.client'

    app.dashboard:
        class: App\Dashboard
        arguments:
            - '@github.client'

    github.client:
        class: Github\Client
        arguments:
            - '@github.client.cached'
        calls:
            - [authenticate, ['6244e67ae95f2307851af09415046def11cfe205', null, http_token]]

    github.client.cached:
        class: Github\HttpClient\CachedHttpClient
        arguments:
            -
                cache_dir: '%kernel.cache_dir%/../../github'
            - '@guzzle.client'

    guzzle.client:
        class: Guzzle\Http\Client
        arguments:
            - 'https://api.github.com'
        calls:
            - [addSubscriber, ['@guzzle.plugin.log']]

    guzzle.plugin.log:
        class: Guzzle\Plugin\Log\LogPlugin
        arguments:
            - '@guzzle.plugin.log.adapter'
            - >
                {request} {code}
                {res_header_ETag}
                {res_header_Last-Modified}
                {res_header_X-RateLimit-Remaining}

    guzzle.plugin.log.adapter:
        class: Guzzle\Log\ClosureLogAdapter
        arguments:
            - '@app.guzzle.plugin.log.adapter.logger'

    app.guzzle.plugin.log.adapter.logger:
        class: App\Guzzle\Log\Logger
        arguments:
            - '@logger'

    jms.serializer.handler.generator:
        class: App\Serializer\Handler\GeneratorHandler
        tags:
            - { name: jms_serializer.subscribing_handler }

